version: "3"

# This file is used to configure the images deployed to Docker Hub

services:
  frontend:
    build:
      context: ..
      dockerfile: .docker-hub/frontend/Dockerfile
    image: ecamp/ecamp3-frontend:latest

  backend:
    build:
      context: ..
      dockerfile: .docker-hub/backend/Dockerfile
    image: ecamp/ecamp3-backend:latest
