jobs:
  include:
    - stage: test
      name: "Backend tests"
      language: php

      # list any PHP version you want to test against
      php:
        # using major version aliases
        # aliased to 5.3.10
        - 7.2

      # optionally specify a list of environments, for example to test different RDBMS
      env:
        - DB=sqlite env=test

      cache:
        directories:
          - vendor

      # execute any number of scripts before the test run, custom env's are available as variables
      # before_script:
      #  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS eCamp3dev_UnitTest;" -uroot; fi

      # omitting "script:" will default to phpunit
      # use the $DB env variable to determine the phpunit.xml to use
      # script: phpunit --configuration phpunit_$DB.xml --coverage-text

      before_script:
          - cd backend
          - composer install --no-interaction
          - composer di-generate-aot
          - cd ..

      script:
          - cd backend
          - mkdir -p build/logs
          - composer test
          - composer cs-check
          - cd ..

      after_script:
          - cd backend
          - vendor/bin/php-coveralls
          - cd ..
    
    - stage: test
      name: "Frontend tests"
      language: node_js
      node_js: '10'
      env:
        - NODE_ENV=development
      cache: npm
      before_install:
        - cd frontend/

      install:
        - npm install

      script:
        - npm run test:unit
        - npm run test:e2e:ci

      after_script:
        - cat ./data/coverage/lcov.info | coveralls


