language: generic

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - name: "Backend tests"
      stage: test
      language: php
      php:
        - 7.4.2
      env:
        - DB=sqlite env=test
        - COVERALLS_PARALLEL=true
      cache:
        directories:
          - vendor
      before_script:
          - cd backend
          - composer install --no-interaction
          - cd ..
      script:
          - cd backend
          - mkdir -p build/logs
          - composer test
          - composer cs-check
          - cd ..
      after_script:
          - backend/vendor/bin/php-coveralls -v --coverage_clover ./backend/build/logs/clover.xml --json_path ./backend/build/logs/coveralls-upload.json
      after_failure:
          - cat /var/log/apache2/error.log


stages:
  - name: test
  - name: "push-images"
    if: branch = devel AND type = push

