version: "3"

services:
  frontend:
    build: ./frontend
    container_name: 'ecamp3-frontend'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app:ro
      - ./frontend/node_modules:/app/node_modules:delegated
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    ports:
      - '80:80'
    links:
      - db
    volumes:
      - ./backend:/var/www/ecamp3:ro
      - ./backend/config/autoload/doctrine.local.dev.php:/var/www/ecamp3/config/autoload/doctrine.local.dev.php:delegated
      - ./backend/data:/var/www/ecamp3/data:delegated

  composer:
    container_name: 'ecamp3-composer'
    restart: 'no'
    image: composer:1.8
    command: bash -c "composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest && composer di-generate-aot"
    volumes:
      - ./backend:/app:ro
      - ./backend/vendor:/app/vendor:delegated
      - ./backend/module/eCampAoT:/app/module/eCampAoT:delegated

  db:
    image: mariadb:10.3
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '8081:80'
    links:
      - db
