version: "3"

services:
  frontend:
    image: node:14
    container_name: 'ecamp3-frontend'
    ports:
      - '3000:3000'
      - '9229:9229' # jest debug 
    stdin_open: true
    tty: true
    user: ${USER_ID:-1000}
    volumes:
      - ./frontend:/app:delegated
      - ./common:/common:delegated
      - ./.cache/npm:/home/node/.npm
      - ./.cache/cypress:/home/node/.cache/Cypress
      - ./.cache/node_modules:/app/node_modules/.cache
    working_dir: /app
    command: ./docker-setup.sh
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_UPDATE_NOTIFIER=false
      - NPM_CONFIG_CACHE=/home/node/.npm
      - CYPRESS_CACHE_FOLDER=/home/node/.cache/Cypress

  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    depends_on:
      - db
      - docker-host
    ports:
      - '3001:3001'
    user: ${USER_ID:-1000}
    volumes:
      - ./backend:/app:delegated
    entrypoint: ./docker-setup.sh

  print:
    image: node:14
    container_name: 'ecamp3-print'
    ports:
      - '3003:3003'
    user: ${USER_ID:-1000}
    volumes:
      - ./print:/app:delegated
      - ./common:/common:delegated
      - ./.cache/npm:/home/node/.npm
      - ./.cache/node_modules:/app/node_modules/.cache
    working_dir: /app
    command: ./docker-setup.sh
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3003
      - NPM_CONFIG_UPDATE_NOTIFIER=false
      - NPM_CONFIG_CACHE=/home/node/.npm
    env_file:
      - ./print/print.env

  composer:
    image: composer:2
    container_name: 'ecamp3-composer'
    restart: 'no'
    command: bash -c "composer install --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest"
    user: ${USER_ID:-1000}
    volumes:
      - ./backend:/app:delegated
      - ./.cache/composer:/tmp/cache

  db:
    image: mariadb:10.5
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3
    ports:
      - '3006:3306'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '3002:80'

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'ecamp3-rabbitmq'
    ports:
      - '3004:15672'

  worker-print-puppeteer:
    build: ./workers/print-puppeteer
    container_name: 'ecamp3-worker-print-puppeteer'
    user: ${USER_ID:-1000}
    volumes:
      - ./workers/print-puppeteer:/app:delegated
      - ./.cache/npm:/home/node/.npm
      - ./.print-data:/app/data
    command: ./docker-setup.sh
    environment:
      - NPM_CONFIG_UPDATE_NOTIFIER=false
      - NPM_CONFIG_CACHE=/home/node/.npm

  worker-print-weasy:
    build: ./workers/print-weasy
    container_name: 'ecamp3-worker-print-weasy'
    user: ${USER_ID:-1000}
    volumes:
      - ./workers/print-weasy:/app:delegated
      - ./.print-data:/app/data

  print-file-server:
    image: halverneus/static-file-server
    container_name: 'ecamp3-print-file-server'
    volumes:
      - ./.print-data:/web
    ports:
      - '3005:8080'
    environment:
      - CORS=true

  docker-host:
    image: qoomon/docker-host
    container_name: 'ecamp3-docker-host-forwarder'
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

volumes:
  db-data:
