version: "3"

services:
  frontend:
    image: node:12.18
    container_name: 'ecamp3-frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:delegated
      - npm-cache:/root/.npm
      - cypress-cache:/root/.cache/Cypress
    working_dir: /app
    command: npm run serve
    environment:
      NODE_ENV: development
  
  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    ports:
      - '3001:80'
    links:
        - db
    volumes:
      - ./backend:/app:delegated
      
  print:
    image: node:12.18
    container_name: 'ecamp3-print'
    ports:
      - '3003:3000'
    volumes:
      - ./print:/app:delegated
      - npm-cache:/root/.npm
    working_dir: /app
    command: npm run dev
    environment:
      - HOST=0.0.0.0

  composer:
    image: composer:1.10
    container_name: 'ecamp3-composer'
    restart: 'no'
    command: bash -c "composer install --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest"
    volumes:
      - ./backend:/app:delegated
      - composer-cache:/tmp/cache

  db:
    image: mariadb:10.5
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '3002:80'
    links:
      - db

volumes:
  npm-cache:
  cypress-cache:
  composer-cache:

  