version: "3"

services:
  frontend:
    image: node:11.13.0-alpine
    container_name: 'ecamp3-frontend'
    ports:
      - '8080:8080'
    working_dir: /app
    entrypoint: /bin/sh -c "npm install && cp -r node_modules/* /node_modules-copy-to-host && npm run serve"
    volumes:
      - ./frontend:/app:delegated
      - node_modules:/app/node_modules
      - ./frontend/node_modules:/node_modules-copy-to-host
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    ports:
      - '80:80'
    links:
      - db
    volumes:
      - ./backend:/var/www/ecamp3:delegated
      - data:/var/www/ecamp3/data
      - ./backend/data/mail:/var/www/ecamp3/data/mail:delegated
      - temp:/var/www/ecamp3/temp
      - vendor:/var/www/ecamp3/vendor

  composer:
    image: composer:1.8
    container_name: 'ecamp3-composer'
    restart: 'no'
    entrypoint: bash -c "composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest && cp -r vendor/* /vendor-copy-to-host && composer di-generate-aot"
    volumes:
      - ./backend:/app:delegated
      - vendor:/app/vendor:delegated
      - ./backend/vendor:/vendor-copy-to-host

  db:
    image: mariadb:10.3
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '8081:80'
    links:
      - db

volumes:
  vendor:
  data:
  temp:
  node_modules:
