version: "3"

services:
  frontend:
    build: ./frontend
    container_name: 'ecamp3-frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:delegated
      - node_modules:/app/node_modules
      - ./frontend/node_modules:/node_modules-copy-to-host
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    ports:
      - '3001:80'
    links:
      - db
    volumes:
      - ./backend:/app:delegated
      - data:/app/data
      - ./backend/data/mail:/app/data/mail:delegated
      - temp:/app/temp
      - vendor:/app/vendor

  composer:
    image: composer:1.8
    container_name: 'ecamp3-composer'
    restart: 'no'
    entrypoint: bash -c "composer install --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest && cp -r vendor/* /vendor-copy-to-host && docker-php-ext-install pdo_mysql && composer di-generate-aot"
    volumes:
      - ./backend:/app:delegated
      - vendor:/app/vendor:delegated
      - ./backend/vendor:/vendor-copy-to-host

  db:
    image: mariadb:10.3
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '3002:80'
    links:
      - db

volumes:
  vendor:
  data:
  temp:
  node_modules:
