version: "3"

services:
  frontend:
    image: node:12.18
    container_name: 'ecamp3-frontend'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app:delegated
      - npm-cache:/root/.npm
      - cypress-cache:/root/.cache/Cypress
      - node-modules-cache:/app/node_modules/.cache
    working_dir: /app
    command: ./docker-setup.sh
    environment:
      NODE_ENV: development
  
  backend:
    build: ./backend
    container_name: 'ecamp3-backend'
    ports:
      - '3001:80'
    volumes:
      - ./backend:/app:delegated
    entrypoint: ./docker-setup.sh  

  print:
    image: node:12.18
    container_name: 'ecamp3-print'
    ports:
      - '3003:3000'
    volumes:
      - ./print:/app:delegated
      - npm-cache:/root/.npm
      - print-node-modules-cache:/app/node_modules/.cache
    working_dir: /app
    command: ./docker-setup.sh
    environment:
      - HOST=0.0.0.0

  composer:
    image: composer:1.10
    container_name: 'ecamp3-composer'
    restart: 'no'
    command: bash -c "composer install --no-interaction --no-plugins --no-scripts --prefer-dist --no-suggest"
    volumes:
      - ./backend:/app:delegated
      - composer-cache:/tmp/cache

  db:
    image: mariadb:10.5
    container_name: 'ecamp3-db'
    environment:
      - MYSQL_DATABASE=ecamp3dev
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=ecamp3
      - MYSQL_PASSWORD=ecamp3
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ecamp3-phpmyadmin'
    ports:
      - '3002:80'

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'ecamp3-rabbitmq'
    ports:
      - '3004:15672'

  worker-print-puppeteer:
    image: buildkite/puppeteer
    container_name: 'ecamp3-worker-print-puppeteer'
    volumes:
      - ./workers/print-puppeteer:/app:delegated
      - npm-cache:/root/.npm
    working_dir: /app
    command: npm run print

  worker-print-weasy:
      build: ./workers/print-weasy
      container_name: 'ecamp3-worker-print-weasy'
      volumes:
        - ./workers/print-weasy:/app:delegated
      working_dir: /app
      command: python print.py

volumes:
  npm-cache:
  cypress-cache:
  composer-cache:
  node-modules-cache:
  print-node-modules-cache:
  db-data:

  