version: "3"

services:
  frontend:
    image: node:12.18
    container_name: 'ecamp3-frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:delegated
      - npm-cache:/root/.npm
      - cypress-cache:/root/.cache/Cypress
    working_dir: /app
    command: npm run serve
    environment:
      NODE_ENV: development

volumes:
  npm-cache:
    external: false
  cypress-cache:
    external: false
  