fos_http_cache:
    tags:
        enabled: true
        annotations:
            enabled: false
    proxy_client:
        varnish:
            tag_mode: purgekeys
            tags_header: xkey-purge
            http:
                servers:
                    - '%env(VARNISH_API_URL)%'
    cache_control:
        defaults:
            overwrite: true
        rules:
            # matches /content_types endpoint
            # matches /camps/133/categories endpoint
            -
                match:
                    path: ^/(content_types|camps/[0-9a-f]*/categories)
                headers:
                    overwrite: true
                    cache_control: { public: true, max_age: 0, s_maxage: 3600 }
                    vary: [Accept, Content-Type, Authorization, Origin]

            # match everything else to set defaults
            -
                match:
                    path: ^/
                headers:
                    overwrite: true
                    cache_control: { no-cache: true, private: true }
                    vary: [Accept, Content-Type, Authorization, Origin]