sentry:
    dsn: '%env(SENTRY_API_DSN)%'
    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
    options:
        environment: '%env(SENTRY_ENVIRONMENT)%'
        integrations:
            - 'Sentry\Integration\IgnoreErrorsIntegration'

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Routing\Exception\ResourceNotFoundException
                    - Symfony\Component\Security\Core\Exception\AccessDeniedException
                    - Symfony\Component\HttpKernel\Exception\HttpException

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
