elasticsearch:
  elasticNode:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limit:
        cpu: 300m
        memory: 500Mi
  persistence:
    resources:
      requests:
        storage: 1Gi

kibana:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limit:
      cpu: 300m
      memory: 500Mi

filebeat:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limit:
      cpu: 200m
      memory: 200Mi
