elastic:
  version: 8.12.1

elasticsearch:
  name: elasticsearch
  version:
  main:
    replicas: 1
    resources:
      requests:
        memory: 800Mi
      limits:
        memory: 1500Mi
    persistence:
      resources:
        requests:
          storage: 10Gi
  data:
    replicas: 0
    resources:
      requests:
        memory: 800Mi
      limits:
        memory: 1500Mi
    persistence:
      resources:
        requests:
          storage: 10Gi

kibana:
  name: kibana
  version:
  resources:
    requests:
      memory: 500Mi
    limits:
      memory: 1Gi

beat:
  name: filebeat
  version:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 120m
      memory: 150Mi
