<template>
  <ContentNodeCard v-resizeobserver.debounce="onResize" v-bind="$props">
    <template #outer>
      <div
        v-if="!layoutMode && (responsibleColumn || !disabled)"
        class="e-storyboard-toolbar px-3 d-flex align-center"
      >
        <v-text-field
          v-if="responsibleColumn"
          v-model="responsibleFilter"
          :label="$t('components.activity.content.storyboard.filterResponsible')"
          prepend-inner-icon="mdi-account-search-outline"
          density="compact"
          variant="outlined"
          hide-details
          clearable
          single-line
          class="e-storyboard-filter flex-grow-0"
        />
        <v-spacer />
        <StoryboardColumnSettings
          v-if="!disabled"
          :show-time="timeColumn"
          :show-responsible="responsibleColumn"
          :show-materials="materialsColumn"
          :parse-time="parseTime"
          :loading="isTogglingColumns"
          @update:show-time="setColumn('timeColumn', $event)"
          @update:show-responsible="setColumn('responsibleColumn', $event)"
          @update:show-materials="setColumn('materialsColumn', $event)"
          @update:parse-time="setColumn('parseTime', $event)"
        />
      </div>
      <component
        :is="isDefaultVariant ? 'table' : 'div'"
        class="w-full"
        :class="{
          'flex-grow-1': !isDefaultVariant,
          'pointer-events-none px-3 pb-3': layoutMode,
        }"
      >
        <thead v-if="isDefaultVariant" :class="{ 'opacity-60': layoutMode }">
          <tr>
            <th v-if="!layoutMode">
              <span class="d-sr-only">
                {{ $t('components.activity.content.storyboard.reorder') }}
              </span>
            </th>
            <th v-if="timeColumn" scope="col" class="text-left">
              {{ $t('contentNode.storyboard.entity.section.fields.column1') }}
            </th>
            <th scope="col" class="text-left">
              {{ $t('contentNode.storyboard.entity.section.fields.column2Html') }}
            </th>
            <th v-if="responsibleColumn" scope="col" class="text-left">
              {{ $t('contentNode.storyboard.entity.section.fields.column3') }}
            </th>
            <th v-if="materialsColumn" scope="col" class="text-left">
              {{ $t('contentNode.storyboard.entity.section.fields.column4') }}
            </th>
            <th>
              <span class="d-sr-only">
                {{ $t('components.activity.content.storyboard.controls') }}
              </span>
            </th>
          </tr>
        </thead>
        <StoryboardSortable
          :entity="contentNode"
          :disabled="layoutMode || disabled"
          :items="sections"
          :layout-mode="layoutMode"
          :is-last-section="isLastSection"
          :show-time="timeColumn"
          :show-responsible="responsibleColumn"
          :show-materials="materialsColumn"
          :parse-time="parseTime"
          :dimmed-keys="dimmedKeys"
          :variant="isDefaultVariant ? 'default' : 'dense'"
          @sort="updateSections"
        />
        <template v-if="!layoutMode && !disabled">
          <tfoot v-if="isDefaultVariant">
            <tr>
              <td :colspan="footerColspan">
                <v-btn
                  block
                  icon
                  variant="text"
                  class="button-add"
                  color="success"
                  rounded
                  :loading="isAdding"
                  @click="addSection"
                >
                  <v-icon size="large">mdi-plus</v-icon>
                </v-btn>
              </td>
            </tr>
          </tfoot>
          <div v-else class="d-flex mx-1 mb-3">
            <v-btn
              block
              icon
              variant="text"
              class="button-add"
              color="success"
              rounded
              :loading="isAdding"
              @click="addSection"
            >
              <v-icon size="large">mdi-plus</v-icon>
            </v-btn>
          </div>
        </template>
      </component>
    </template>
  </ContentNodeCard>
</template>
<script>
import ContentNodeCard from '@/components/activity/content/layout/ContentNodeCard.vue'
import { contentNodeMixin } from '@/mixins/contentNodeMixin.js'

import { errorToMultiLineToast } from '@/components/toast/toasts'
import StoryboardSortable from '@/components/activity/content/storyboard/StoryboardSortable.vue'
import StoryboardColumnSettings from '@/components/activity/content/storyboard/StoryboardColumnSettings.vue'
import { useToast } from 'vue-toastification'

// This is a very poorly implemented polyfill for crypto.randomUUID
// which was generated by ChatGPT. It should under no circumstances
// be used for security/cryptographic purposes. In this component it
// serves the use case of generating unique identifiers for storyboard sections.
// We only employ this polyfill here  because there are apparently some users
// with ancient Safari versions lacking support for randomUUID,
// see https://caniuse.com/mdn-api_crypto_randomuuid
const poorUuidPolyfill = function () {
  function randomDigit() {
    const random = (Math.random() * 16) | 0
    return random.toString(16)
  }

  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    const r = randomDigit()
    const v = c === 'x' ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}

export default {
  name: 'Storyboard',
  components: {
    ContentNodeCard,
    StoryboardSortable,
    StoryboardColumnSettings,
  },
  mixins: [contentNodeMixin],
  props: {
    contentNode: { type: Object, required: true },
  },
  setup() {
    const toast = useToast()
    return { toast }
  },
  data() {
    return {
      isAdding: false,
      isTogglingColumns: false,
      responsibleFilter: '',
      clientWidth: 1000,
    }
  },
  computed: {
    timeColumn() {
      return this.api.get(this.contentNode).data.timeColumn ?? true
    },
    responsibleColumn() {
      return this.api.get(this.contentNode).data.responsibleColumn ?? true
    },
    materialsColumn() {
      return this.api.get(this.contentNode).data.materialsColumn ?? false
    },
    parseTime() {
      return this.api.get(this.contentNode).data.parseTime ?? false
    },
    // Keys of sections whose responsible column does not match the current
    // filter; these are visually dimmed so matches are easy to spot. Empty
    // filter dims nothing.
    dimmedKeys() {
      const filter = (this.responsibleFilter ?? '').trim().toLowerCase()
      if (filter === '') {
        return []
      }
      const sections = this.sections
      return Object.keys(sections).filter(
        (key) => !(sections[key].column3 ?? '').toLowerCase().includes(filter)
      )
    },
    footerColspan() {
      // handle + program + controls are always present; the optional columns
      // (time, responsible, material) add to the span when shown.
      return (
        3 +
        (this.timeColumn ? 1 : 0) +
        (this.responsibleColumn ? 1 : 0) +
        (this.materialsColumn ? 1 : 0)
      )
    },
    sections() {
      const sections = this.api.get(this.contentNode).data.sections

      // workaround because our API return an empty array instead of empty object, if there is no section
      // this could be removed later, when no empty sections objects are in the DB anymore
      if (Array.isArray(sections) && sections.length === 0) {
        return {}
      }

      return sections
    },
    isLastSection() {
      return Object.keys(this.sections).length === 1
    },
    isDefaultVariant() {
      return this.clientWidth > 910
    },
  },
  mounted() {
    this.clientWidth = this.$el.getBoundingClientRect().width
  },
  methods: {
    onResize({ width }) {
      this.clientWidth = width
    },
    async addSection() {
      this.isAdding = true

      const sectionId =
        typeof self.crypto?.randomUUID !== 'function'
          ? poorUuidPolyfill()
          : self.crypto.randomUUID()
      try {
        // TODO: consider adding item to StoryboardSortable eagerly (should be easy, now that uuid is generated locally)
        await this.contentNode.$patch({
          data: {
            sections: {
              [sectionId]: {
                column1: '',
                column2Html: '',
                column3: '',
                column4: '',
                position: Object.keys(this.sections).length + 1,
              },
            },
          },
        })
      } catch (error) {
        this.toast.error(errorToMultiLineToast(error))
      }

      this.isAdding = false
    },

    async setColumn(column, value) {
      this.isTogglingColumns = true
      try {
        await this.contentNode.$patch({
          data: {
            [column]: !!value,
          },
        })
      } catch (error) {
        this.toast.error(errorToMultiLineToast(error))
      }
      this.isTogglingColumns = false
    },

    async updateSections(payload) {
      try {
        await this.contentNode.$patch({
          data: {
            sections: payload,
          },
        })
      } catch (error) {
        this.toast.error(errorToMultiLineToast(error))
      }
    },
  },
}
</script>

<style scoped lang="scss"></style>
