services:
  create-backup:
    build:
      context: ../db-backup-restore-image
      dockerfile: Dockerfile
    volumes:
      - ./create-backup.sh:/create-backup.sh
    command:
      - sh
      - "-x"
      - /create-backup.sh
    env_file: .env
