apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api-http
      protocol: TCP
      name: api-http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
