apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.name" . }}-configmap
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
data:
  ADDITIONAL_TRUSTED_HOSTS: {{ .Values.domain | quote }}
  COOKIE_PREFIX: {{ include "api.cookiePrefix" . | quote }}
  APP_ENV: {{ .Values.api.appEnv | quote }}
  APP_DEBUG: {{ .Values.api.appDebug | quote }}
  {{- if .Values.api.dataMigrationsDir }}
  DATA_MIGRATIONS_DIR: {{ .Values.api.dataMigrationsDir | quote }}
  {{- end }}
  CORS_ALLOW_ORIGIN: {{ include "frontend.url" . | quote }}
  TRUSTED_PROXIES: "{{ join "," .Values.api.trustedProxies }}"
  {{- if .Values.api.sentryDsn }}
  SENTRY_API_DSN: {{ .Values.api.sentryDsn | quote }}
  SENTRY_ENVIRONMENT: {{ .Values.domain | quote }}
  {{- else }}
  SENTRY_API_DSN: {{ "" | quote }}
  {{- end }}
  FRONTEND_BASE_URL: {{ include "frontend.url" . | quote }}
  CADDY_GLOBAL_OPTIONS: {{ .Values.api.caddyGlobalOptions | quote }}
