apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-platform.fullname" . }}-configmap
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
data:
  API_DOMAIN: {{ .Values.apiDomain | quote }}
  APP_ENV: {{ .Values.php.appEnv | quote }}
  APP_DEBUG: {{ .Values.php.appDebug | quote }}
  CORS_ALLOW_ORIGIN: {{ .Values.php.corsAllowOrigin | quote }}
  TRUSTED_PROXIES: "{{ join "," .Values.php.trustedProxies }}"
  MERCURE_URL: "http://{{ include "api-platform.fullname" . }}/.well-known/mercure"
  MERCURE_PUBLIC_URL: {{ .Values.mercure.publicUrl | default "http://127.0.0.1/.well-known/mercure" | quote }}
