{{- if .Values.apiCache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apiCache.name" . }}
  labels:
    {{- include "apiCache.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apiCache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apiCache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}-api-cache
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.apiCache.image.repository }}:{{ .Values.apiCache.image.tag | default .Values.imageTag }}"
          imagePullPolicy: {{ .Values.apiCache.image.pullPolicy }}
          ports:
            - name: api-cache-http
              containerPort: {{ .Values.apiCache.varnishHttpPort }}
              protocol: TCP
          env:
            - name: VARNISH_SIZE
              value: "{{ .Values.apiCache.varnishSize }}"
            - name: VARNISH_HTTP_PORT
              value: "{{ .Values.apiCache.varnishHttpPort }}"
          resources:
            {{- toYaml .Values.apiCache.resources | nindent 12 }}
          volumeMounts:
            - name: vcl-configmap
              mountPath: /etc/varnish
      volumes:
      - name: vcl-configmap
        configMap:
          name: {{ include "apiCache.name" . }}-vcl-configmap
{{- end }}