#
# Migrates the database after installing or upgrading the chart.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "app.name" . }}-db-migrate"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: "{{ include "app.name" . }}-pre-install"
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate-job
          {{ template "api.phpContainer" . }}
          command:
            - "/bin/sh"
            - "-c"
            - "php bin/console dbal:run-sql -q \"SELECT 1\" 2>&1 && php bin/console doctrine:migrations:migrate --no-interaction"
      volumes:
      - name: php-socket
        emptyDir: {}
      - name: jwt-keypair
        secret:
          secretName: {{ include "api.name" . }}
          items:
            - key: jwt-public-key
              path: public.pem
            - key: jwt-private-key
              path: private.pem