{{- if not .Values.postgresql.enabled and .Values.postgresql.dropDBOnUninstall }} # only create the database if using an external PostgreSQL server
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "app.name" . }}-post-delete"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "app.name" . }}-post-delete"
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-delete-job
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Values.imageTag }}"
          command: ["php", "bin/console", "doctrine:database:drop", "--if-exists", "-f"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: admin-database-url
                  name: {{ include "app.name" . }}-hooks
{{- end }}