{{- if not .Values.postgresql.enabled }} # db admin credentials are only needed if using an external PostgreSQL server
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-hooks
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  admin-database-url: {{ .Values.postgresql.adminUrl | default .Values.postgresql.url | b64enc | quote }}
{{- end }}