apiVersion: v1
kind: Secret
metadata:
  name: {{ include "print.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.print.sentryDsn }}
  sentry-dsn: {{ .Values.print.sentryDsn | b64enc | quote }}
  {{- else}}
  sentry-dsn: ""
  {{- end }}

  {{- if .Values.print.browserlessToken }}
  browserless-token: {{ .Values.print.browserlessToken | quote }}
  {{- else}}
  browserless-token: ""
  {{- end }}
