name: "Tests: API performance test"

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
  schedule:
    - cron: '51 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  api-performance-test:
    name: 'API performance test'
    if: contains(github.event.pull_request.labels.*.name, 'api-performance-test!') || github.event_name != 'pull_request'
    uses: ./.github/workflows/reusable-api-performance-test.yml
