name: Dependency Check

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "42 3 * * *"

env:
  USER_ID: 1001

jobs:
  api-check-dependencies:
    name: "Api Platform check dependencies"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.3'
          tools: composer:2.2.0
          coverage: xdebug

      - run: composer update --lock --no-interaction --no-plugins --no-scripts --prefer-dist
        working-directory: api
