name: Dependency Check

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  schedule:
    - cron: '42 3 * * *'

env:
  USER_ID: 1001

jobs:
  api-check-dependencies:
    name: 'Api Platform check dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.10'
          tools: composer:2.6.0
          coverage: xdebug

      - run: composer update --lock --no-interaction --no-plugins --no-scripts --prefer-dist
        working-directory: api
