name: Deploy to dev.ecamp3.ch

on:
  repository_dispatch:
    types: [ images-pushed ]

jobs:
  only-on-deployment-branches:
    name: Only on deployment branches
    if: ${{ github.event.client_payload.deployment_name != null }}
    runs-on: ubuntu-latest
    steps:

      - run: 'echo "Ref: ${{ github.event.client_payload.ref }}"'

      - run: 'echo "SHA: ${{ github.event.client_payload.sha }}"'

      - run: 'echo "Deployment name: ${{ github.event.client_payload.deployment_name }}"'

  deploy:
    name: "Deploy"
    needs: only-on-deployment-branches
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      # TODO actually install the feature branch deployment, using `helm upgrade --install xyz`

      # TODO if not dev.ecamp3.ch, write a comment on the PR, containing the URL of the feature branch deployment
      - name: Create comment
        if: ${{ github.event.client }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment

      # TODO remove the old deployment logic
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEVEL_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEVEL_SSH_KNOWN_HOSTS }}

      - uses: ./.github/actions/deploy
        with:
          commit-sha: ${{ github.event.client_payload.sha }}
          ssh-host: ${{ secrets.DEVEL_SSH_HOST }}
          shared-cookie-domain: ${{ secrets.DEVEL_SHARED_COOKIE_DOMAIN }}
          frontend-url: ${{ secrets.DEVEL_FRONTEND_URL }}
          print-server-url: ${{ secrets.DEVEL_PRINT_SERVER_URL }}
          print-file-server-url: ${{ secrets.DEVEL_PRINT_FILE_SERVER_URL }}
          mail-server-url: ${{ secrets.DEVEL_MAIL_SERVER_URL }}
          sentry-frontend-dsn: ${{ secrets.DEVEL_SENTRY_FRONTEND_DSN }}
          sentry-print-dsn: ${{ secrets.DEVEL_SENTRY_PRINT_DSN }}
          sentry-worker-print-puppeteer-dsn: ${{ secrets.DEVEL_SENTRY_WORKER_PRINT_PUPPETEER_DSN }}
          sentry-worker-print-weasy-dsn: ${{ secrets.DEVEL_SENTRY_WORKER_PRINT_WEASY_DSN }}
          rabbitmq-host: ${{ secrets.DEVEL_RABBITMQ_HOST }}
          rabbitmq-port: ${{ secrets.DEVEL_RABBITMQ_PORT }}
          rabbitmq-vhost: ${{ secrets.DEVEL_RABBITMQ_VHOST }}
          rabbitmq-user: ${{ secrets.DEVEL_RABBITMQ_USER }}
          rabbitmq-pass: ${{ secrets.DEVEL_RABBITMQ_PASS }}
          api-url: ${{ secrets.DEVEL_API_URL }}
          api-app-secret: ${{ secrets.DEVEL_API_APP_SECRET }}
          api-database-url: ${{ secrets.DEVEL_API_DATABASE_URL }}
          api-jwt-passphrase: ${{ secrets.DEVEL_API_JWT_PASSPHRASE }}
