name: Continuous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  backend-cs-check:
    name: "Backend: PHP CS Fixer"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: OskarStark/php-cs-fixer-ga@2.17.0
        with:
          args: --dry-run --diff --config=backend/.php_cs
