name: PR

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - 'renovate/**'

jobs:
  no-meeting-discuss-label:
    name: No "Meeting Discuss" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@1fa57210051fe9c31c4cb84e66becfcaf7058d04 # v2
        if: github.event_name == 'pull_request'
        with:
          mode: exactly
          count: 0
          labels: "Meeting Discuss"
