name: PR

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - 'renovate/**'

jobs:
  # test
  no-meeting-discuss-label:
    name: No "Meeting Discuss" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@c0f708ca21f539fc66bac255181c40d7196c4cdc # tag=v2
        if: github.event_name == 'pull_request'
        with:
          mode: exactly
          count: 0
          labels: "Meeting Discuss"
