name: PR

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  no-meeting-discuss-label:
    name: No "Meeting Discuss" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "Meeting Discuss"
