name: Build docker images and push them to Docker Hub

on:
  repository_dispatch:
    types: [ ci-passed ]
  pull_request:
    types: [ labeled, reopened, synchronize ]

jobs:
  only-on-deployment-branches:
    name: Only on deployment branches
    if: ${{ ('refs/heads/devel' == github.event.client_payload.ref) || contains(github.event.pull_request.labels.*.name, 'deploy!') }}
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.extract.outputs.ref || github.event.pull_request.head.ref }}
      sha: ${{ steps.extract.outputs.sha || github.event.pull_request.head.sha }}
      deployment-name: ${{ steps.extract.outputs.deployment-name }}
    steps:
      - id: extract
        env:
          PR_NUMBER: ${{ (github.event.pull_request && github.event.pull_request.number) || '' }}
        run: |
          if [ "$PR_NUMBER" = "" ]; then
            echo "::set-output name=ref::${{ github.event.client_payload.ref }}"
            echo "::set-output name=sha::${{ github.event.client_payload.sha }}"
            echo "::set-output name=deployment-name::dev"
          else
            echo "::set-output name=ref::${{ github.event.pull_request.head.ref }}"
            echo "::set-output name=sha::${{ github.event.pull_request.head.sha }}"
            echo "::set-output name=deployment-name::pr-$PR_NUMBER"
          fi

      - env:
          REF: ${{ steps.extract.outputs.ref }}
          SHA: ${{ steps.extract.outputs.sha }}
          DEPLOYMENT_NAME: ${{ steps.extract.outputs.deployment-name }}
        run: 'echo "Ref: $REF, SHA: $SHA, deployment name: $DEPLOYMENT_NAME"'

  push-frontend-to-docker-hub:
    name: "Push frontend to Docker Hub"
    needs: only-on-deployment-branches
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}

      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ecamp/ecamp3-frontend
          dockerfile: .docker-hub/frontend/Dockerfile
          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'

  push-api-to-docker-hub:
    name: "Push api to Docker Hub"
    needs: only-on-deployment-branches
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}

      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ecamp/ecamp3-api
          dockerfile: api/Dockerfile
          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'
          path: './api'
          target: api_platform_php

  push-caddy-to-docker-hub:
    name: "Push caddy to Docker Hub"
    needs: only-on-deployment-branches
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}

      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ecamp/ecamp3-caddy
          dockerfile: api/Dockerfile
          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'
          path: './api'
          target: api_platform_caddy_prod

  push-print-to-docker-hub:
    name: "Push print to Docker Hub"
    needs: only-on-deployment-branches
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}

      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ecamp/ecamp3-print
          dockerfile: .docker-hub/print/Dockerfile
          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'

#  push-worker-print-puppeteer-to-docker-hub:
#    name: "Push worker-print-puppeteer to Docker Hub"
#    needs: only-on-deployment-branches
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
#        with:
#          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}
#
#      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: ecamp/ecamp3-worker-print-puppeteer
#          dockerfile: .docker-hub/worker-print-puppeteer/Dockerfile
#          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'
#
#  push-worker-print-weasy-to-docker-hub:
#    name: "Push worker-print-weasy to Docker Hub"
#    needs: only-on-deployment-branches
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
#        with:
#          ref: ${{ needs.only-on-deployment-branches.outputs.sha }}
#
#      - uses: docker/build-push-action@3e7a4f6646880c6f63758d73ac32392d323eaf8f # renovate: tag=v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: ecamp/ecamp3-worker-print-weasy
#          dockerfile: .docker-hub/worker-print-weasy/Dockerfile
#          tags: 'latest,${{ needs.only-on-deployment-branches.outputs.sha }}'

  images-pushed-event:
    name: "Send out image push success event"
    needs:
      - only-on-deployment-branches
      - push-frontend-to-docker-hub
      - push-api-to-docker-hub
      - push-caddy-to-docker-hub
      - push-print-to-docker-hub
#      - push-worker-print-puppeteer-to-docker-hub
#      - push-worker-print-weasy-to-docker-hub
    runs-on: ubuntu-latest
    steps:

      - uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4 # renovate: tag=v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: images-pushed
          client-payload: '{"ref": "${{ needs.only-on-deployment-branches.outputs.ref }}", "sha": "${{ needs.only-on-deployment-branches.outputs.sha }}", "deployment_name": "${{ needs.only-on-deployment-branches.outputs.deployment-name }}"}'
