name: sync

on:
  schedule:
  - cron: '20 * * * *' # Sync at 20 minutes past every full hour, to avoid peak load of GitHub actions

jobs:
  sync-deploy:
    name: Sync the deploy branch with devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shitiomatic/forkbacon@master
        with:
          upstream_url: "https://github.com/ecamp/ecamp3.git"
          upstream_branch: "devel"
          branch: "deploy-dev.ecamp3.ch"
          method: "rebase"
